package pse.trippy.aiservice.places.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import pse.trippy.aiservice.places.dto.PlaceInsightsRequest;
import pse.trippy.aiservice.places.dto.PlaceInsightsResponse;
import pse.trippy.aiservice.places.dto.PlaceInsightsResponse.PlaceInsight;
import pse.trippy.aiservice.places.dto.PlaceInsightsResponse.Review;
import pse.trippy.aiservice.places.dto.PlaceRankRequest;
import pse.trippy.aiservice.places.dto.PlaceRankResponse;
import pse.trippy.aiservice.places.dto.PlaceRankResponse.Ranking;
import pse.trippy.aiservice.recommendation.service.OllamaRecommendationClient;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Model-written place reviews and top-3 rankings for the trip day-map search.
 *
 * <p>Primary path is the local Ollama model (same client the itinerary
 * recommendations use); every failure degrades to a deterministic seeded
 * fallback so the endpoint never errors out mid-demo. Stateless — nothing is
 * persisted.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class PlaceInsightsService {

    private static final Duration INSIGHTS_TIMEOUT = Duration.ofSeconds(60);
    private static final Duration RANK_TIMEOUT = Duration.ofSeconds(40);

    private static final String INSIGHTS_SYSTEM_PROMPT = """
            You write realistic, varied user reviews for real-world places.
            Respond with STRICT JSON only, no prose, exactly this shape:
            {"places":[{"id":"<same id as given>","rating":4.4,"reviewCount":213,
            "reviews":[{"author":"Lena","rating":5,"when":"2 months ago","text":"..."}]}]}
            Rules: one entry per given place, keep the exact ids; rating is one decimal between 3.2 and 4.9;
            reviewCount is an integer between 15 and 950; exactly 2 reviews per place; review rating is an
            integer 3-5; "when" is a relative time like "3 weeks ago"; texts are 1-2 concrete sentences that
            fit the place's name, category and address (mention a dish, view, staff, vibe, price...);
            vary the authors' first names; never include markdown or comments.
            """;

    private static final String RANK_SYSTEM_PROMPT = """
            You are a sharp local guide. Given a traveller's search intent and candidate places with
            ratings and review snippets, pick the top 3 and explain why.
            Respond with STRICT JSON only, no prose, exactly this shape:
            {"summary":"one sentence overall verdict",
            "rankings":[{"id":"<same id as given>","rank":1,"reason":"..."}]}
            Rules: exactly 3 rankings (or one per place if fewer than 3 given), ranks 1..3 with no ties;
            keep the exact ids; each reason is 1-2 concrete sentences grounded in the ratings, review
            snippets, category or location — never generic filler; never include markdown or comments.
            """;

    private final OllamaRecommendationClient ollama;
    private final ObjectMapper mapper;

    public PlaceInsightsResponse insights(PlaceInsightsRequest request) {
        if (ollama.isEnabled()) {
            try {
                String content = ollama.chatJson(
                        INSIGHTS_SYSTEM_PROMPT, buildInsightsUserPrompt(request), INSIGHTS_TIMEOUT);
                List<PlaceInsight> parsed = parseInsights(content, request);
                if (!parsed.isEmpty()) {
                    log.info("Place insights generated by model for {} place(s)", parsed.size());
                    return new PlaceInsightsResponse("AI", ollama.model(), parsed);
                }
            } catch (Exception ex) {
                log.warn("Place insights fell back reason={}", ex.getMessage());
            }
        }
        return new PlaceInsightsResponse("FALLBACK", "fallback", fallbackInsights(request));
    }

    public PlaceRankResponse rank(PlaceRankRequest request) {
        if (ollama.isEnabled()) {
            try {
                String content = ollama.chatJson(
                        RANK_SYSTEM_PROMPT, buildRankUserPrompt(request), RANK_TIMEOUT);
                PlaceRankResponse parsed = parseRank(content, request);
                if (parsed != null && !parsed.rankings().isEmpty()) {
                    log.info("Place ranking generated by model query='{}' top={}",
                            request.query(), parsed.rankings().size());
                    return parsed;
                }
            } catch (Exception ex) {
                log.warn("Place ranking fell back reason={}", ex.getMessage());
            }
        }
        return fallbackRank(request);
    }

    // ------------------------------------------------------------------ prompts

    private String buildInsightsUserPrompt(PlaceInsightsRequest request) {
        StringBuilder sb = new StringBuilder("Write ratings and reviews for these places:\n");
        for (PlaceInsightsRequest.PlaceRef p : request.places()) {
            sb.append("- id=").append(p.id())
                    .append(" | name=").append(p.name());
            if (isSet(p.category())) sb.append(" | category=").append(p.category());
            if (isSet(p.address())) sb.append(" | address=").append(p.address());
            sb.append('\n');
        }
        return sb.toString();
    }

    private String buildRankUserPrompt(PlaceRankRequest request) {
        StringBuilder sb = new StringBuilder("Search intent: ").append(request.query().trim()).append('\n');
        sb.append("Candidates:\n");
        for (PlaceRankRequest.RankPlace p : request.places()) {
            sb.append("- id=").append(p.id()).append(" | name=").append(p.name());
            if (isSet(p.category())) sb.append(" | category=").append(p.category());
            if (isSet(p.address())) sb.append(" | address=").append(p.address());
            if (p.rating() != null) sb.append(" | rating=").append(p.rating());
            if (p.reviewCount() != null) sb.append(" | reviews=").append(p.reviewCount());
            if (p.reviewSnippets() != null && !p.reviewSnippets().isEmpty()) {
                sb.append(" | snippets=\"").append(String.join("\" / \"", p.reviewSnippets())).append('"');
            }
            sb.append('\n');
        }
        return sb.toString();
    }

    // ------------------------------------------------------------------ parsing

    private List<PlaceInsight> parseInsights(String content, PlaceInsightsRequest request) throws Exception {
        JsonNode root = mapper.readTree(content);
        Map<String, JsonNode> byId = new LinkedHashMap<>();
        for (JsonNode node : root.path("places")) {
            String id = node.path("id").asText("");
            if (!id.isBlank()) byId.put(id, node);
        }

        List<PlaceInsight> out = new ArrayList<>();
        for (PlaceInsightsRequest.PlaceRef ref : request.places()) {
            JsonNode node = byId.get(ref.id());
            if (node == null) {
                out.add(fallbackInsight(ref));
                continue;
            }
            double rating = clamp(node.path("rating").asDouble(4.2), 3.0, 5.0);
            int reviewCount = (int) clamp(node.path("reviewCount").asInt(120), 5, 5000);
            List<Review> reviews = new ArrayList<>();
            for (JsonNode r : node.path("reviews")) {
                String text = r.path("text").asText("").trim();
                if (text.isBlank()) continue;
                reviews.add(new Review(
                        r.path("author").asText("Traveller"),
                        (int) clamp(r.path("rating").asInt(4), 1, 5),
                        r.path("when").asText("recently"),
                        text));
                if (reviews.size() == 2) break;
            }
            if (reviews.isEmpty()) {
                out.add(fallbackInsight(ref));
            } else {
                out.add(new PlaceInsight(ref.id(), round1(rating), reviewCount, reviews));
            }
        }
        return out;
    }

    private PlaceRankResponse parseRank(String content, PlaceRankRequest request) throws Exception {
        JsonNode root = mapper.readTree(content);
        Map<String, PlaceRankRequest.RankPlace> byId = new LinkedHashMap<>();
        for (PlaceRankRequest.RankPlace p : request.places()) byId.put(p.id(), p);

        List<Ranking> rankings = new ArrayList<>();
        for (JsonNode node : root.path("rankings")) {
            String id = node.path("id").asText("");
            PlaceRankRequest.RankPlace place = byId.get(id);
            String reason = node.path("reason").asText("").trim();
            if (place == null || reason.isBlank()) continue;
            rankings.add(new Ranking(id, rankings.size() + 1, place.name(), reason));
            if (rankings.size() == 3) break;
        }
        if (rankings.isEmpty()) return null;
        String summary = root.path("summary").asText("").trim();
        return new PlaceRankResponse("AI", ollama.model(),
                summary.isBlank() ? null : summary, rankings);
    }

    // ----------------------------------------------------------------- fallback

    private List<PlaceInsight> fallbackInsights(PlaceInsightsRequest request) {
        return request.places().stream().map(this::fallbackInsight).toList();
    }

    /** Deterministic per-place seed so repeated searches show stable numbers. */
    private PlaceInsight fallbackInsight(PlaceInsightsRequest.PlaceRef ref) {
        int seed = Math.abs(ref.id().hashCode());
        double rating = round1(3.6 + seed % 12 / 10.0);
        int reviewCount = 40 + seed % 420;
        String what = isSet(ref.category()) ? ref.category().toLowerCase() : "spot";
        List<Review> reviews = List.of(
                new Review(FALLBACK_AUTHORS[seed % FALLBACK_AUTHORS.length], 5,
                        (1 + seed % 10) + " weeks ago",
                        ref.name() + " is a lovely " + what + " — friendly staff and it never felt too crowded."),
                new Review(FALLBACK_AUTHORS[(seed / 7 + 3) % FALLBACK_AUTHORS.length], 4,
                        (1 + seed % 5) + " months ago",
                        "Solid choice in the area. Prices are fair and the atmosphere is relaxed."));
        return new PlaceInsight(ref.id(), rating, reviewCount, reviews);
    }

    private PlaceRankResponse fallbackRank(PlaceRankRequest request) {
        List<PlaceRankRequest.RankPlace> sorted = request.places().stream()
                .sorted(Comparator.comparingDouble(
                        (PlaceRankRequest.RankPlace p) -> p.rating() != null ? p.rating() : 0.0).reversed())
                .limit(3)
                .toList();
        List<Ranking> rankings = new ArrayList<>();
        for (int i = 0; i < sorted.size(); i++) {
            PlaceRankRequest.RankPlace p = sorted.get(i);
            StringBuilder reason = new StringBuilder();
            if (p.rating() != null) {
                reason.append("Rated ").append(p.rating()).append("★");
                if (p.reviewCount() != null) reason.append(" across ").append(p.reviewCount()).append(" reviews");
                reason.append(i == 0
                        ? " — the strongest score among these results."
                        : " — a close runner-up on rating.");
            } else {
                reason.append("A well-matched pick for \"").append(request.query()).append("\" in this area.");
            }
            rankings.add(new Ranking(p.id(), i + 1, p.name(), reason.toString()));
        }
        return new PlaceRankResponse("FALLBACK", "fallback",
                "Ranked by rating while the AI guide is unavailable.", rankings);
    }

    private static final String[] FALLBACK_AUTHORS = {
            "Mia", "Jonas", "Sofia", "Luca", "Emma", "Noah", "Clara", "Felix", "Ida", "Ben"
    };

    private static boolean isSet(String v) {
        return v != null && !v.isBlank();
    }

    private static double clamp(double v, double min, double max) {
        return Math.max(min, Math.min(max, v));
    }

    private static double round1(double v) {
        return Math.round(v * 10.0) / 10.0;
    }
}
