package pse.trippy.aiservice.places.dto;

import java.util.List;

/**
 * Ratings + short reviews for a batch of searched places.
 *
 * @param source {@code AI} when generated by the local model, {@code FALLBACK} otherwise
 * @param model  model that produced the insights (or {@code fallback})
 * @param places one entry per requested place, same ids as the request
 */
public record PlaceInsightsResponse(
        String source,
        String model,
        List<PlaceInsight> places
) {

    public record PlaceInsight(
            String id,
            double rating,
            int reviewCount,
            List<Review> reviews
    ) {
    }

    public record Review(
            String author,
            int rating,
            String when,
            String text
    ) {
    }
}
