package pse.trippy.aiservice.places.dto;

import java.util.List;

/**
 * Top-3 place ranking with per-place reasoning.
 *
 * @param source   {@code AI} when generated by the local model, {@code FALLBACK} otherwise
 * @param model    model that produced the ranking (or {@code fallback})
 * @param summary  one-line overall verdict
 * @param rankings up to three entries, rank 1 first
 */
public record PlaceRankResponse(
        String source,
        String model,
        String summary,
        List<Ranking> rankings
) {
    public PlaceRankResponse {
        rankings = List.copyOf(rankings);
    }

    public record Ranking(
            String placeId,
            int rank,
            String name,
            String reason
    ) {
    }
}
