spring:
  config:
    import: "optional:file:../../infra/docker/.env[.properties]"
  application:
    name: payment-service
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:trippy_db}?currentSchema=payment_schema
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: PaymentServicePool
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: payment_schema
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST:trippy}

server:
  port: 8086

stripe:
  secret:
    key: sk_test_51Ts9T4HPsFWQmqJBggOSkqquxjb4kC32L3HrP1xAmqfhv67qpj1L3tt2iU5kJdHF1oo1IBXlqcOFYijkY7wusg9z00AItLgFJ0
  publishable:
    key: pk_test_51Ts9T4HPsFWQmqJBxaHvGlfQxBg7WOxp0x1WxOZoIGHPhdqQde9E4Z6mA5Ob3hCLkzoza3YCKDVCJFQDBBPJw6o6006ij6IYoJ
  webhook:
    secret: whsec_c350d06c1820e8da40991c5c282388e95c9d17d69c76df7052fe43004c7a15c9
  price:
    premium: price_1TsA87HPsFWQmqJB2izPhg7w
    enterprise: price_1TsAEnHPsFWQmqJBP6iOeXC4


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    pse.trippy.paymentservice: INFO
    org.hibernate.SQL: WARN
    org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator: ERROR
