package pse.trippy.aiservice.recommendation.dto;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Grouped-by-day itinerary suggestions returned to the trip AI sidebar.
 *
 * @param tripId      owning trip (echoed back), may be null
 * @param model       model that produced the options (or {@code fallback})
 * @param source      {@code AI} when generated by Ollama, {@code FALLBACK} otherwise
 * @param generatedAt server timestamp of generation
 * @param days        one entry per requested day, each with up to three options
 */
public record RecommendationResponse(
        UUID tripId,
        String model,
        String source,
        Instant generatedAt,
        List<DayRecommendations> days
) {

    public record DayRecommendations(
            int dayNumber,
            List<RecommendationOption> options
    ) {
    }

    public record RecommendationOption(
            UUID id,
            String vibe,
            String title,
            String startTime,
            String endTime,
            BigDecimal cost,
            String currency,
            String mapsUrl,
            String notes
    ) {
    }
}
